[build-system]
requires = ["setuptools", "wheel", "Cython >= 3.0.0"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build-frontend = "build"
before-build = "pip install git+https://bitbucket.org/jankowsk/mtcutils.git@master"
